/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ClienteDAO;
import dao.ProdutoDAO;
import dao.VendaDAO;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Produto;
import model.Venda;

public class VendaGUI extends javax.swing.JFrame {

    /**
     * Creates new form VendaGUI
     */
    public VendaGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitCadProd = new javax.swing.JLabel();
        btAdicionar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cxClienteID = new javax.swing.JTextField();
        cxQuantidade = new javax.swing.JTextField();
        cxProdutoID = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cx = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btConsultar1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        cxDataForm = new javax.swing.JFormattedTextField();
        btAdicionar1 = new javax.swing.JButton();
        btAdicionar2 = new javax.swing.JButton();
        btConsultar2 = new javax.swing.JButton();

        rtTitCadProd.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        rtTitCadProd.setText("Cadastro de Cliente");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Vendas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btAdicionar.setBackground(new java.awt.Color(102, 102, 255));
        btAdicionar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel5.setText("Quantidade:");

        cxClienteID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cxClienteID.setToolTipText("XXX.XXX.XXX-XX");
        cxClienteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxClienteIDActionPerformed(evt);
            }
        });

        cxQuantidade.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cxQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxQuantidadeActionPerformed(evt);
            }
        });

        cxProdutoID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cxProdutoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxProdutoIDActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GERENCIAR VENDAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        cx.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cx.setText("ID do Produto:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setText("ID do Cliente:");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel12.setText("Cadastrar Venda");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel13.setText("Data da Venda:");

        btConsultar1.setBackground(new java.awt.Color(102, 102, 255));
        btConsultar1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btConsultar1.setForeground(new java.awt.Color(255, 255, 255));
        btConsultar1.setText("Listar");
        btConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultar1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Lista de Vendas");

        tbProdutos.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Cliente", "ID Produto", "Produto", "Quantidade", "Data", "Lucro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProdutos.setRowHeight(30);
        jScrollPane2.setViewportView(tbProdutos);
        if (tbProdutos.getColumnModel().getColumnCount() > 0) {
            tbProdutos.getColumnModel().getColumn(0).setPreferredWidth(120);
        }

        try {
            cxDataForm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cxDataForm.setToolTipText("Ano/Mes/Dia");
        cxDataForm.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cxDataForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxDataFormActionPerformed(evt);
            }
        });

        btAdicionar1.setBackground(new java.awt.Color(102, 102, 255));
        btAdicionar1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btAdicionar1.setForeground(new java.awt.Color(255, 255, 255));
        btAdicionar1.setText("Ver Relatório Mensal");
        btAdicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionar1ActionPerformed(evt);
            }
        });

        btAdicionar2.setBackground(new java.awt.Color(102, 102, 255));
        btAdicionar2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btAdicionar2.setForeground(new java.awt.Color(255, 255, 255));
        btAdicionar2.setText("Limpar");
        btAdicionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionar2ActionPerformed(evt);
            }
        });

        btConsultar2.setBackground(new java.awt.Color(102, 102, 255));
        btConsultar2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btConsultar2.setForeground(new java.awt.Color(255, 255, 255));
        btConsultar2.setText("Sair");
        btConsultar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(cx)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cxClienteID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxProdutoID)
                            .addComponent(cxDataForm, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(cxQuantidade)))
                    .addComponent(btAdicionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAdicionar2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btConsultar2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addGap(182, 182, 182))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(210, 210, 210)
                    .addComponent(jLabel12)
                    .addContainerGap(828, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cxClienteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cx)
                            .addComponent(cxProdutoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cxDataForm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(btAdicionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAdicionar2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btConsultar2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(124, 124, 124)
                    .addComponent(jLabel12)
                    .addContainerGap(410, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        try {
            // 1. Validar e buscar objetos dependentes.
            int produtoId = Integer.parseInt(cxProdutoID.getText());
            String clienteId = cxClienteID.getText();
            
            // Validação básica para garantir que os campos não estão vazios.
            if (clienteId.trim().isEmpty() || cxDataForm.getText().trim().replace("-", "").isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Consulta o produto para garantir que ele existe.
            ProdutoDAO produtoController = new ProdutoDAO();
            Produto produto = produtoController.consultarProduto(produtoId);
            if (produto == null) {
                JOptionPane.showMessageDialog(this, "Produto com ID " + produtoId + " não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Consulta o cliente para garantir que ele existe.
            ClienteDAO clienteController = new ClienteDAO();
            Cliente cliente = clienteController.consultarCliente(clienteId);
            if (cliente == null) {
                JOptionPane.showMessageDialog(this, "Cliente com CPF/CNPJ " + clienteId + " não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 2. Criar o objeto Venda com os dados validados.
            Venda venda = new Venda();
            venda.setCliente(cliente);
            venda.setProduto(produto);
            venda.setDataVenda(LocalDate.parse(cxDataForm.getText()));
            venda.setQuantidade(Integer.parseInt(cxQuantidade.getText()));
            
            // 3. Chamar o DAO para inserir a venda. A lógica transacional complexa está no DAO.
            VendaDAO vendaController = new VendaDAO();
            vendaController.inserir(venda);
            
            // 4. Feedback de sucesso e atualização da interface.
            JOptionPane.showMessageDialog(this, "Venda registrada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limpar();
            listarTab();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID do produto e quantidade devem ser números válidos.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao registrar venda: \n" + ex.getMessage(), "Erro de Banco de Dados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void cxClienteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxClienteIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxClienteIDActionPerformed

    private void cxQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxQuantidadeActionPerformed

    private void cxProdutoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxProdutoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxProdutoIDActionPerformed

    private void btConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultar1ActionPerformed
        listarTab();
    }//GEN-LAST:event_btConsultar1ActionPerformed

    private void cxDataFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxDataFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxDataFormActionPerformed

    private void btAdicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionar1ActionPerformed
        String mesStr = JOptionPane.showInputDialog(this, "Informe o mês (1-12)", "Relatório Mensal", JOptionPane.QUESTION_MESSAGE);
        String anoStr = JOptionPane.showInputDialog(this, "Informe o ano (AAAA)", "Relatório Mensal", JOptionPane.QUESTION_MESSAGE);
        
        try {
            int mes = Integer.parseInt(mesStr);
            int ano = Integer.parseInt(anoStr);
            
            if (mes < 1 || mes > 12 || ano < 2000) {
                 JOptionPane.showMessageDialog(this, "Por favor, insira um mês e ano válidos.", "Entrada Inválida", JOptionPane.ERROR_MESSAGE);
                 return;
            }

            RelatorioVendas relatorio = new RelatorioVendas(mesStr, anoStr);
            relatorio.setVisible(true);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mês e ano devem ser números.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btAdicionar1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarTab();
    }//GEN-LAST:event_formWindowActivated

    private void btAdicionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionar2ActionPerformed
        limpar();
    }//GEN-LAST:event_btAdicionar2ActionPerformed

    private void btConsultar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultar2ActionPerformed
        sair();
    }//GEN-LAST:event_btConsultar2ActionPerformed

    public void listarTab(){
        DefaultTableModel modelo = (DefaultTableModel) tbProdutos.getModel();
        modelo.setRowCount(0);
        
        try {
            VendaDAO vendaController = new VendaDAO();
            List<Venda> vendas = vendaController.listarVendas();
            for (Venda venda : vendas) { 
                modelo.addRow(new Object[]{
                    venda.getCliente().getIdentificador(),
                    venda.getProduto().getProdutoId(),
                    venda.getProduto().getNome(),
                    venda.getQuantidade(),
                    venda.getDataVenda(),
                    venda.getValorTotal()
                });
            }
            
            DefaultTableCellRenderer centralizarRenderer = new DefaultTableCellRenderer();
            centralizarRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            for (int i = 0; i < tbProdutos.getColumnCount(); i++) {
                tbProdutos.getColumnModel().getColumn(i).setCellRenderer(centralizarRenderer);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao listar vendas: \n" + ex.getMessage(), "Erro de Banco de Dados", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    public void limpar(){
        cxClienteID.setText("");
        cxProdutoID.setText("");
        cxQuantidade.setText("");
        cxDataForm.setText("");
        cxClienteID.requestFocus();
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION);
        if(resp == JOptionPane.YES_OPTION){
            dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAdicionar1;
    private javax.swing.JButton btAdicionar2;
    private javax.swing.JButton btConsultar1;
    private javax.swing.JButton btConsultar2;
    private javax.swing.JLabel cx;
    private javax.swing.JTextField cxClienteID;
    private javax.swing.JFormattedTextField cxDataForm;
    private javax.swing.JTextField cxProdutoID;
    private javax.swing.JTextField cxQuantidade;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel rtTitCadProd;
    private javax.swing.JTable tbProdutos;
    // End of variables declaration//GEN-END:variables
}
